git:
  depth: 3
language: python
python: "2.7"
arch:
  - amd64
  - ppc64le
  - arm64
env: CONTAINER=centos:7
services:
  - docker
install:
    - docker pull ${CONTAINER}
    - docker build -t leapp-tests -f utils/docker-tests/Dockerfile utils/docker-tests

script:
    - docker run --rm -v ${PWD}:/payload leapp-tests
